package org.parasol.model.audit;

public enum AuditEventType {
	SERVICE_STARTED,
	SERVICE_COMPLETED,
	SERVICE_ERROR,
	RESPONSE_RECEIVED,
	TOOL_EXECUTED,
	INPUT_GUARDRAIL_EXECUTED,
	OUTPUT_GUARDRAIL_EXECUTED
}
